### ISSUE TITLE
Decrease Lure max level to 5 or rework the enchant itself

### ISSUE THREAD

**Issue by NattoRiisa** [Hardel-DW/BeyondEnchant#1]
This is due to the Lure enchant subtracting 5 seconds, whilst a random period of 5-30 seconds is applied
Unless if the lure enchant has been reworked to subtracting 2.5 seconds instead of 5 seconds:
If lure time is less than 0, it will create a new timer for the next tick, but after subtracting 30 seconds, it will always generate a timer, which causes the fish to note bite the rod :P

**Comment by Hardel-DW** [comment]
It does seem appropriate.
Otherwise there was a solution to define 5, 
10 and 15 seconds for the first 3 levels.
And 2 seconds for each level between the levels 4 to 10.

**Comment by NattoRiisa** [comment]
That solution works too, but i am unaware on how to implement it like that ;;

**Comment by Hardel-DW** [comment]
Avec lookup, et linear c'est possidble

```json
{
  "description": {
    "translate": "enchantment.minecraft.lure"
  },
  "supported_items": "#minecraft:enchantable/fishing",
  "weight": 2,
  "max_level": 3,
  "min_cost": {
    "base": 15,
    "per_level_above_first": 9
  },
  "max_cost": {
    "base": 65,
    "per_level_above_first": 9
  },
  "anvil_cost": 4,
  "slots": [
    "mainhand"
  ],
  "effects": {
    "minecraft:fishing_time_reduction": [
      {
        "effect": {
          "type": "minecraft:add",
          "value": {
            "type": "minecraft:lookup",
            "values": [
              5,
              10,
              15
            ],
            "fallback": {
              "type": "minecraft:linear",
              "base": 9,
              "per_level_above_first": 2
            }
          }
        }
      }
    ]
  }
}

```
