### ISSUE TITLE
Beyond Enchant Mod Problem

### ISSUE THREAD

**Issue by uknownerror** [Hardel-DW/BeyondEnchant#3]
I tried to use the newest version of beyond enchant which is 1.2.0 for 1.21 fabric and im not quite sure why but i cant figure out how to get the higher levels of the enchantments, im also using neo enchants+ but i cant get any levels higher than the normal ones. Ive tried to combine them in an anvil in creative and try to do it with an enchantment table but I cant get it to work even though I see it on my mod list and it should theoretically be working. If you need the mod list im using i can send it.

**Comment by uknownerror** [comment]
UPDATE: I can see sharpness 10 on a book but I cant get the higher levels for neo enchants+

**Comment by Hardel-DW** [comment]
They're just very rare. That's normal. It's easier with villager exchanges, or in the coffers of structures.
It's designed to not break the gameplay
