### ISSUE TITLE
some enchants doesnt show up even in creative mod and i cant also combine some enchants to its next level because of that

### ISSUE THREAD

**Issue by chopper355** [Hardel-DW/BeyondEnchant#6]
![2024-10-25_16 57 10](https://github.com/user-attachments/assets/5d1f3b68-5e4b-4237-ad95-7e31fe4b837c)
![2024-10-25_16 57 07](https://github.com/user-attachments/assets/4b5adfc8-edf7-4986-8718-fdd2e0b21f28)
![2024-10-25_16 56 43](https://github.com/user-attachments/assets/869062b7-e988-47c6-935a-bfec2cd85742)
![2024-10-25_16 56 41](https://github.com/user-attachments/assets/b544a13b-a361-49f6-afa3-2892f980769d)
Enchants doesnt combine.
And it says loot table error report to mod/datapack author.

**Comment by chopper355** [comment]
I currently get errors/crashes whenever i try to play the game. Currently i cannot help you atleast i cannot do the thing that requires me to type /data thing in game but when im available i can.Here is the level.dat file. Theres too many mods on my world i hope thats not thing that causes the issue.
[level.zip](https://github.com/user-attachments/files/17532806/level.zip)

**Comment by Hardel-DW** [comment]
![image](https://github.com/user-attachments/assets/318a5809-164b-431f-a7ef-b64634a1b5b7)

By pure chance, really by pure chance.
I work for dnt and have imported their datapack into my site.

And I discover that this famous enchantment comes from them.
So it's not a bug. It's the name of the enchantment.

**Comment by Hardel-DW** [comment]
It's an enchantment from Dungeon and Taverns

**Comment by chopper355** [comment]
oh okay thats a really big coincidence. But i can ignore that not the problem the problem is i cannot combine enchants on anvil. When i combine sharpness Vs they become sharpness V again. Thats why i wanted this mod. Because it tells you that you need to grind more for the best enchantment. It is hard to do that with anvil. It requires lots of exp and stuff but i think that would make the game more immersive. I dont like the idea of grinding the game just by staying afk on a village.

**Comment by chopper355** [comment]
i also really liked dnt mod. It makes the game more enjoyable.However i didnt like their enchants because it felt like it was really far away from vanilla experience. And i added nofun dnt mod which disables dnt enchantments.

**Comment by Hardel-DW** [comment]
![image](https://github.com/user-attachments/assets/05a836b5-2d58-47c4-8ad5-f88224de7826)
![image](https://github.com/user-attachments/assets/ebae1ad8-5f7e-40cb-9b3f-bfed4425ac08)

The fact that the combination doesn't work. Maybe it's another mod/datapack cause the problem.
Maybe a mod wich modify vanilla enchantments after me.

I saw that you have a lot of mods, probably one of them is a problem.
Beyond doesn't use any Java code, just configuration file provided by Mojang. A bug like this can't come from Beyond

**Comment by chopper355** [comment]
Yeah you were right thanks for the help. Disabling enchantment plus mod fixed this. I dont know how modders decide what type of mod  they want to create but this type of mods are essential for the game. Thanks for your hardwork.

**Comment by Master-64** [comment]
I can confirm that the `Enchants Plus` mod directly conflicts with this mod, making it so that this mod effectively does nothing. Should probably be mentioned as a direct incompatibility.
